import { useState } from 'react';
import type { Project, Page, Section } from '../types';
import { generateBlueprintMd } from '../lib/prompts';
import { buildBuilderPrompt, combos, promptFileName, readmePromptLines, type ExportTargets } from '../lib/builderPrompts';
import { checkFabrication, factCheckMd } from '../lib/pageAssets';
import { changesMd, cleanPrototypeHtml, readChanges } from '../lib/changeLog';
import { siteMd } from '../lib/kitFiles';

async function screenshotToBase64(data: string): Promise<string> {
  if (data.startsWith('data:')) return data.split(',')[1];
  if (data.startsWith('http')) {
    try {
      const resp = await fetch(data);
      const blob = await resp.blob();
      const arrayBuf = await blob.arrayBuffer();
      const bytes = new Uint8Array(arrayBuf);
      let binary = '';
      for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
      return btoa(binary);
    } catch { return ''; }
  }
  return data;
}

export function useExport() {
  const [exporting, setExporting] = useState(false);

  const exportZip = async (
    project: Project,
    pages: Page[],
    allSections: Record<string, Section[]>,
    screenshotMap: Record<string, string> = {},
    includeScreenshots = false,
    targets: ExportTargets = { tools: ['bolt'], outputs: ['react'] },
    /** Builder Kit: its own ZIP name and README.md */
    opts: { zipName?: string; readme?: string } = {},
  ) => {
    setExporting(true);
    try {
      // Loaded only when a ZIP is exported (keeps it out of the first download)
      const { default: JSZip } = await import('jszip');
      const zip = new JSZip();
      const globals = project.globals;
      const multiPage = pages.length > 1;

      const activeScreenshotMap = includeScreenshots ? screenshotMap : {};
      const hasScreenshots = includeScreenshots && Object.values(screenshotMap).some(Boolean);

      // One first-message prompt per selected AI builder
      const pkg = {
        projectName: project.name,
        hasDesign: !!project.design_md,
        hasPrototype: pages.some(p => p.generated_html),
        hasChanges: pages.some(p => p.generated_html || readChanges(p).length),
        hasCopy: pages.some(p => p.copy_md),
        hasImages: pages.some(p => p.images_md),
        hasScreenshots,
        hasSite: true,
        sectionCount: pages.length === 1 ? (allSections[pages[0].id] || []).length : undefined,
        pages: pages.map(p => p.page_name),
      };
      const promptTargets: ExportTargets = combos(targets).length ? targets : { tools: ['bolt'], outputs: ['react'] };
      for (const c of combos(promptTargets)) zip.file(promptFileName(c.tool, c.output), buildBuilderPrompt(c.tool, c.output, pkg));

      if (project.design_md) {
        zip.file('design.md', project.design_md);
      }

      for (const page of pages) {
        const sections = allSections[page.id] || [];
        const blueprintMd = generateBlueprintMd(globals, page, sections);
        const filename = multiPage
          ? `blueprint-${page.slug || page.page_name.toLowerCase().replace(/\s+/g, '-')}.md`
          : 'blueprint.md';
        zip.file(filename, blueprintMd);

        // Verbatim copy, real images and the fact check (only when captured at import)
        const suffix = multiPage ? `-${page.slug || page.page_name.toLowerCase().replace(/\s+/g, '-')}` : '';
        if (page.copy_md) {
          zip.file(`copy${suffix}.md`, page.copy_md);
          zip.file(`fact-check${suffix}.md`, factCheckMd(page.page_name, checkFabrication(sections, page.copy_md)));
        }
        if (page.images_md) zip.file(`images${suffix}.md`, page.images_md);
        zip.file(`site${suffix}.md`, siteMd(project, page));

        // The approved prototype (with all later changes) + the change list
        if (page.generated_html) zip.file(`prototype${suffix}.html`, cleanPrototypeHtml(page.generated_html));
        if (page.generated_html || readChanges(page).length) zip.file(`changes${suffix}.md`, changesMd(page, sections));

        const screenshotData = activeScreenshotMap[page.id];
        if (screenshotData) {
          const base64 = await screenshotToBase64(screenshotData);
          if (base64) {
            const ssFilename = multiPage
              ? `screenshot-${page.slug || page.page_name.toLowerCase().replace(/\s+/g, '-')}.jpg`
              : 'screenshot.jpg';
            zip.file(ssFilename, base64, { base64: true });
          }
        }
      }

      const screenshotPages = pages.filter(p => activeScreenshotMap[p.id]);
      const readme = `# ${project.name} — Blueprint Package

Generated by Sharpen.Studio Blueprint Maker
URL: ${project.url}
Date: ${new Date().toISOString().split('T')[0]}

## Files
${readmePromptLines(promptTargets)}
- design.md — Complete design system (colors, fonts, spacing, components)
${multiPage
  ? pages.map(p => `- site-${p.slug || p.page_name.toLowerCase().replace(/\s+/g, '-')}.md — ${p.page_name}: navigation, footer, SEO`).join('\n')
  : '- site.md — Navigation, footer, social links and SEO title / description'}
${multiPage
  ? pages.map(p => `- blueprint-${p.slug}.md — ${p.page_name} page structure`).join('\n')
  : '- blueprint.md — Page structure and section definitions'}
${pages.some(p => p.copy_md)
  ? (multiPage
      ? pages.filter(p => p.copy_md).map(p => `- copy-${p.slug}.md — ${p.page_name}: exact page text (use verbatim)\n- fact-check-${p.slug}.md — ${p.page_name}: blueprint text not found on the real page`).join('\n')
      : '- copy.md — Exact page text, captured without AI (use verbatim)\n- fact-check.md — Blueprint text not found on the real page (review before publishing)')
  : ''}
${pages.some(p => p.images_md)
  ? (multiPage
      ? pages.filter(p => p.images_md).map(p => `- images-${p.slug}.md — ${p.page_name}: real image URLs by section`).join('\n')
      : '- images.md — Real image URLs, grouped by section')
  : ''}
${pages.some(p => p.generated_html)
  ? (multiPage
      ? pages.filter(p => p.generated_html).map(p => `- prototype-${p.slug}.html — ${p.page_name}: the approved prototype (open in a browser)\n- changes-${p.slug}.md — ${p.page_name}: changes approved on the prototype`).join('\n')
      : '- prototype.html — The approved prototype, including all later changes (open in a browser)\n- changes.md — Changes approved on the prototype (keep them)')
  : ''}
${screenshotPages.length > 0
  ? (multiPage
      ? screenshotPages.map(p => `- screenshot-${p.slug}.jpg — ${p.page_name} visual reference`).join('\n')
      : '- screenshot.jpg — Visual reference screenshot')
  : ''}

## How to Use
1. Open your AI tool of choice
2. Paste the matching prompt-<tool>-<output>.txt as your first message
3. Attach design.md, the blueprint.md file(s), site.md and — if present — copy.md, images.md, prototype.html and changes.md
${screenshotPages.length > 0 ? '4. Attach screenshot file(s) for visual reference\n5. Hit send and review the output' : '4. Hit send and review the output'}
`;
      if (opts.readme) zip.file('README.md', opts.readme);
      else zip.file('README.txt', readme);

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = opts.zipName ?? `${project.name.replace(/\s+/g, '-').toLowerCase()}-blueprint.zip`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setExporting(false);
    }
  };

  const downloadFile = (content: string, filename: string, mimeType = 'text/plain') => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = async (text: string): Promise<boolean> => {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      return false;
    }
  };

  return { exportZip, downloadFile, copyToClipboard, exporting };
}
