import { useState } from 'react';
import JSZip from 'jszip';
import type { Project, Page, Section } from '../types';
import { generateBlueprintMd, getMasterPrompt } from '../lib/prompts';

async function screenshotToBase64(data: string): Promise<string> {
  if (data.startsWith('data:')) return data.split(',')[1];
  if (data.startsWith('http')) {
    try {
      const resp = await fetch(data);
      const blob = await resp.blob();
      const arrayBuf = await blob.arrayBuffer();
      const bytes = new Uint8Array(arrayBuf);
      let binary = '';
      for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
      return btoa(binary);
    } catch { return ''; }
  }
  return data;
}

export function useExport() {
  const [exporting, setExporting] = useState(false);

  const exportZip = async (
    project: Project,
    pages: Page[],
    allSections: Record<string, Section[]>,
    screenshotMap: Record<string, string> = {},
    includeScreenshots = false
  ) => {
    setExporting(true);
    try {
      const zip = new JSZip();
      const globals = project.globals;
      const multiPage = pages.length > 1;

      const activeScreenshotMap = includeScreenshots ? screenshotMap : {};
      const hasScreenshots = includeScreenshots && Object.values(screenshotMap).some(Boolean);

      zip.file('prompt.txt', getMasterPrompt(hasScreenshots));

      if (project.design_md) {
        zip.file('design.md', project.design_md);
      }

      for (const page of pages) {
        const sections = allSections[page.id] || [];
        const blueprintMd = generateBlueprintMd(globals, page, sections);
        const filename = multiPage
          ? `blueprint-${page.slug || page.page_name.toLowerCase().replace(/\s+/g, '-')}.md`
          : 'blueprint.md';
        zip.file(filename, blueprintMd);

        const screenshotData = activeScreenshotMap[page.id];
        if (screenshotData) {
          const base64 = await screenshotToBase64(screenshotData);
          if (base64) {
            const ssFilename = multiPage
              ? `screenshot-${page.slug || page.page_name.toLowerCase().replace(/\s+/g, '-')}.jpg`
              : 'screenshot.jpg';
            zip.file(ssFilename, base64, { base64: true });
          }
        }
      }

      const screenshotPages = pages.filter(p => activeScreenshotMap[p.id]);
      const readme = `# ${project.name} — Blueprint Package

Generated by Sharpen.Studio Blueprint Maker
URL: ${project.url}
Date: ${new Date().toISOString().split('T')[0]}

## Files
- prompt.txt — Master instructions for the AI
- design.md — Complete design system (colors, fonts, spacing, components)
${multiPage
  ? pages.map(p => `- blueprint-${p.slug}.md — ${p.page_name} page structure`).join('\n')
  : '- blueprint.md — Page structure and section definitions'}
${screenshotPages.length > 0
  ? (multiPage
      ? screenshotPages.map(p => `- screenshot-${p.slug}.jpg — ${p.page_name} visual reference`).join('\n')
      : '- screenshot.jpg — Visual reference screenshot')
  : ''}

## How to Use
1. Open your AI tool of choice
2. Copy the contents of prompt.txt as your opening message
3. Attach design.md and the blueprint.md file(s)
${screenshotPages.length > 0 ? '4. Attach screenshot file(s) for visual reference\n5. Hit send and review the output' : '4. Hit send and review the output'}
`;
      zip.file('README.txt', readme);

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${project.name.replace(/\s+/g, '-').toLowerCase()}-blueprint.zip`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setExporting(false);
    }
  };

  const downloadFile = (content: string, filename: string, mimeType = 'text/plain') => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = async (text: string): Promise<boolean> => {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      return false;
    }
  };

  return { exportZip, downloadFile, copyToClipboard, exporting };
}
